language: java
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: Pa+UdhnG4sIbD9fS8Em4sF5arYyohFRLvwh4LfFpEIsn4/6VUVIqqzVbDHy15iAzcvF2hn7DigWVrHVj+XUx1hhq0XVUwW1VfWW3BlRRiZlcd1gv6fJzcRyzOT89AC729zcizNQWPw7pq3eU5gjh1wRdX3sK9FtkV/Zo/+AV7nM=
  # SONATYPE_PASSWORD
  - secure: bABFMS6dYrcNjVxTUxEBtcDTX5YDpeW9fYfRYQH6G1lJWXtw/rTlFbaRl8DLIl8UG9n9+84k00mmzsl6YIAb06RydDrifbT9VkHmVA5yeN5gWXiBniDihHoV3xiuDq0X06RE+1qqT7FQGAk56l5hYvuC121RmqFJs3BQPQET8ts=
  # GPG_PASSPHRASE
  - secure: OAPP79UJVrrop3ywpiILXxKUHTo0TI1jEGouWcVssvDvR6pQvuCDTI9DGUmo3/fo7LP8pL0b6yakCsrmqsdQkDaBJptZbxtXubx9RWoxnFFMAYZ0MUa34QGH25WzQF9Qc5cWMojxlcHO2e3UwDWVxvkhkUCPr2YdNbzwSpLJ1bc=
  # GPG_KEYID
  - GPG_KEYID: 0DD20E21
  # GPG_KEY
  - secure: NAkrcCgVxoq20Mvx4WQhN49zGcRqZK8V4Prsrltjl9eylpjncu/SROcBXFRcwQ/2Xkd/N3WOMDolexnFiYUlwDTlkdIZwPFv8HbsOMNS6Fdr6Tl7quMakLCOr+eArUbKL9uyInuLRGSqDelnoZNJhERVN59w4dC6tQ2pHWUZyTE=
